#!/bin/sh

# Specify the directory where `protoc` command exists
proto_bin_dir=/usr/local/bin

protobuf_jar_version=3.1.0
protobuf_jar=protobuf-java-$protobuf_jar_version.jar
protobuf_jar_path=../classpath/$protobuf_jar

if [ ! -e ../classpath ]; then
  echo '../classpath directory does not exist. Run `./gradlew package` first.'
  exit
fi

# AddressBookProtos Setting
proto_proto2syntax=addressbook_proto2_syntax.proto
proto_proto3syntax=addressbook_proto3_syntax.proto
package_path=com/example/tutorial
outer_classname=AddressBookProtos

generated_java_file_path=$package_path/$outer_classname.java
generated_class_file_path=$package_path/$outer_classname*.class


function generate_jar() {
  proto_bin_dir=$1
  proto_file=$2
  jar_basename=$3
  $proto_bin_dir/protoc --java_out=./ $proto_file
  javac -classpath $protobuf_jar_path $generated_java_file_path
  jar cvf ./${jar_basename}.jar $generated_class_file_path 1>/dev/null
  mv $generated_java_file_path $package_path/$jar_basename.java
  rm -f $generated_class_file_path
}

echo "Generating jar from proto2-syntax .proto ..."
jar_basename=${outer_classname}Proto2Syntax
generate_jar $proto_bin_dir $proto_proto2syntax $jar_basename
echo "Done."

echo "Generating jar from proto3-syntax .proto ..."
jar_basename=${outer_classname}Proto3Syntax
generate_jar $proto_bin_dir $proto_proto3syntax $jar_basename
echo "Done."
